name: CI
on:
  push:
    branches:
      - development
      - master
  pull_request:
    branches:
      - development
      - master
jobs:
    run-tests:
        runs-on: ubuntu-latest
        name: java unit tests
        steps:
          - name : Checkout code
            uses: actions/checkout@v4
          - name: Set up java
            uses: actions/setup-java@v4
            with:
              distribution: 'adopt'
              java-version: 11
          - name: Setup gradle
            uses: gradle/gradle-build-action@v3
          - name: Run tests
            run: ./gradlew test
