name: CI
on:
  push:
    branches:
      - development
      - master
  pull_request:
    branches:
      - development
      - master
jobs:
    run-tests:
        runs-on: ubuntu-latest
        name: java unit tests
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Building docker image
            run: docker build -t local .
          - name: Running gradle test
            run: docker run -v $PWD:/app -w /app local ./gradlew test
