# cerete a new github action that will build and test the project using the gradle wrapper and docker
name: CI
on:
  push:
    branches:
      - development
      - master
  pull_request:
    branches:
      - development
      - master
jobs:
    run-tests:
        runs-on: ubuntu-latest
        name: java unit tests
        container:
          image: composer:latest
          volumes:
            - my-app:/app
        steps:
          - name: Running composer install
            run: composer install
          - name: Running gradle test
            run: ./gradlew test
